---
## Sources
# https://www.cyberciti.biz/faq/ansible-apt-update-all-packages-on-ubuntu-debian-linux/

- name: Install common packages
  become: yes
  apt:
    name: '{{ base_apt_packages }}'
    state: present
  register: setup_ubuntu
  notify: reboot_check

- name: Set default locale
  become: yes
  lineinfile:
    dest: /etc/default/locale
    regexp: 'LANG=.+'
    line: 'LANG={{ base_default_locale }}'
    state: present
  register: setup_ubuntu
  notify: reboot_check

- name: Enable locale
  become: yes
  locale_gen:
    name: '{{ base_default_locale }}'
    state: present
  register: setup_ubuntu
  notify: reboot_check