---
## Sources
# https://www.cyberciti.biz/faq/ansible-apt-update-all-packages-on-ubuntu-debian-linux/

- name: Install common packages
  become: yes
  apt:
    name: '{{ base_apt_packages }}'
    state: present
  register: setup_ubuntu

- name: Set default locale
  become: yes
  lineinfile:
    dest: /etc/default/locale
    regexp: 'LANG=.+'
    line: 'LANG={{ base_default_locale }}'
    state: present
  register: setup_ubuntu

- name: Enable locale
  become: yes
  locale_gen:
    name: '{{ base_default_locale }}'
    state: present
  register: setup_ubuntu

- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 10
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 60
    test_command: whoami
  become: true
  when: setup_ubuntu.changed